package com.chocolate.webservice.cxfinterceptor;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.0
 * 2015-05-31T01:14:03.395+08:00
 * Generated source version: 3.1.0
 * 
 */
@WebService(targetNamespace = "http://cxfinterceptor.webservice.chocolate.com/", name = "IInterceptorDemo")
@XmlSeeAlso({ObjectFactory.class})
public interface IInterceptorDemo {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "addStudent", targetNamespace = "http://cxfinterceptor.webservice.chocolate.com/", className = "com.chocolate.webservice.cxfinterceptor.AddStudent")
    @WebMethod
    @ResponseWrapper(localName = "addStudentResponse", targetNamespace = "http://cxfinterceptor.webservice.chocolate.com/", className = "com.chocolate.webservice.cxfinterceptor.AddStudentResponse")
    public boolean addStudent(
        @WebParam(name = "arg0", targetNamespace = "")
        com.chocolate.webservice.cxfinterceptor.Student arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getStudent", targetNamespace = "http://cxfinterceptor.webservice.chocolate.com/", className = "com.chocolate.webservice.cxfinterceptor.GetStudent")
    @WebMethod
    @ResponseWrapper(localName = "getStudentResponse", targetNamespace = "http://cxfinterceptor.webservice.chocolate.com/", className = "com.chocolate.webservice.cxfinterceptor.GetStudentResponse")
    public com.chocolate.webservice.cxfinterceptor.Student getStudent();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAllStudent", targetNamespace = "http://cxfinterceptor.webservice.chocolate.com/", className = "com.chocolate.webservice.cxfinterceptor.GetAllStudent")
    @WebMethod
    @ResponseWrapper(localName = "getAllStudentResponse", targetNamespace = "http://cxfinterceptor.webservice.chocolate.com/", className = "com.chocolate.webservice.cxfinterceptor.GetAllStudentResponse")
    public java.util.List<com.chocolate.webservice.cxfinterceptor.Student> getAllStudent();
}
