package com.chocolate.webservice.cxfinterceptor;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.0
 * 2015-05-31T01:14:03.429+08:00
 * Generated source version: 3.1.0
 * 
 */
@WebServiceClient(name = "InterceptroIMPLService", 
                  wsdlLocation = "http://10.228.64.178:8989/day01_ws/datatypews?wsdl",
                  targetNamespace = "http://cxfinterceptor.webservice.chocolate.com/") 
public class InterceptroIMPLService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://cxfinterceptor.webservice.chocolate.com/", "InterceptroIMPLService");
    public final static QName InterceptroIMPLPort = new QName("http://cxfinterceptor.webservice.chocolate.com/", "InterceptroIMPLPort");
    static {
        URL url = null;
        try {
            url = new URL("http://10.228.64.178:8989/day01_ws/datatypews?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(InterceptroIMPLService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://10.228.64.178:8989/day01_ws/datatypews?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public InterceptroIMPLService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public InterceptroIMPLService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InterceptroIMPLService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public InterceptroIMPLService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public InterceptroIMPLService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public InterceptroIMPLService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns IInterceptorDemo
     */
    @WebEndpoint(name = "InterceptroIMPLPort")
    public IInterceptorDemo getInterceptroIMPLPort() {
        return super.getPort(InterceptroIMPLPort, IInterceptorDemo.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IInterceptorDemo
     */
    @WebEndpoint(name = "InterceptroIMPLPort")
    public IInterceptorDemo getInterceptroIMPLPort(WebServiceFeature... features) {
        return super.getPort(InterceptroIMPLPort, IInterceptorDemo.class, features);
    }

}
